-- User Table
CREATE TABLE _user
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255)                             NOT NULL,
    github_id  VARCHAR(255),
    password   VARCHAR(255)                             NOT NULL,
    role       VARCHAR(50)                              NOT NULL, -- Assuming roles like 'USER', 'ADMIN' are short strings
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email)
);

INSERT INTO _user (first_name, last_name, email, password, role)
VALUES ('Alice', 'Smith', 'alice@example.com', '$2a$10$vijzIeofJKEIBByFk4Gov.3RDmZTtQbChx51heq//phWExKRO6iMq', 'USER'),
       ('Bob', 'Thompson', 'bob@example.com', '$2a$10$vijzIeofJKEIBByFk4Gov.3RDmZTtQbChx51heq//phWExKRO6iMq', 'USER'),
       ('John', 'Doe', 'johndoe@example.com', '$2a$10$vijzIeofJKEIBByFk4Gov.3RDmZTtQbChx51heq//phWExKRO6iMq', 'USER'),
       ('Jane', 'Dane', 'janedane@example.com', '$2a$10$vijzIeofJKEIBByFk4Gov.3RDmZTtQbChx51heq//phWExKRO6iMq', 'USER');