-- Create the book table with a foreign key constraint on author_id
CREATE TABLE _book
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    isbn        VARCHAR(17)  NOT NULL,
    description TEXT,
    author_id   INTEGER      NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES _user (id)
);

-- Insert initial book data, ensuring author_id corresponds to existing users
INSERT INTO _book (title, isbn, description, author_id)
VALUES ('Spring Boot Basics', '978-1234567890', 'A comprehensive guide to Spring Boot.', 1),
       ('Advanced Java Programming', '978-0987654321', 'Deep dive into advanced Java topics.', 2),
       ('Data structures and Algorithms', '978-0933614344', 'Learn Data structures for Java Pro', 3),
       ('Spring 6 and Boot 3', '978-0921324370', 'From beginner to GURU in Spring', 4);