spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  jwtRefreshExpirationMs: 86400000

frontend:
  url: ${FRONTEND_URL}  # Frontend URL as environment variable

social:
  feature:
    oauth2:
      enabled: true

quartz:
  scheduler:
    cron: "0 0 0 * * ?"  # Every day at midnight
