spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
  expiration: 86400000
  jwtRefreshExpirationMs: 86400000

frontend:
  url: ${FRONTEND_URL}  # Frontend URL as environment variable